// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAM_4IOaWJ2jufuaXjKAhh4uIYAqFqDAk',
    appId: '1:501243301896:android:ba65976b4f7176bccd81bd',
    messagingSenderId: '501243301896',
    projectId: 'golfapp-new-70ef4',
    storageBucket: 'golfapp-new-70ef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkLfH1JcbyxNJz8OJo-PeNGQdqYNX3qI',
    appId: '1:501243301896:ios:d01e5cd047509e0bcd81bd',
    messagingSenderId: '501243301896',
    projectId: 'golfapp-new-70ef4',
    storageBucket: 'golfapp-new-70ef4.firebasestorage.app',
    androidClientId: '501243301896-g176hvfni7fhh9557p06q0ve722e8vh8.apps.googleusercontent.com',
    iosClientId: '501243301896-6hadb1cu6a3khhfhr327pn9el8drl2vl.apps.googleusercontent.com',
    iosBundleId: 'jp.homebear.evcharge',
  );
}
