// WORLD TIME ZONE
// https://www.karhukoti.com/WorldTimeDate/?tz=North%20Asia%20East%20Standard%20Time
Map<String, int> getListTimeZoneID = <String, int>{
  "Samoa Standard Time": -13 * 60,
  "Dateline Standard Time": -12 * 60,
  "UTC-11": -11 * 60,
  "Hawaiian Standard Time": -10 * 60,
  "Alaskan Standard Time": -9 * 60,
  "Pacific Standard Time": -8 * 60,
  "Pacific Standard Time (Mexico)": -8 * 60,
  "Mountain Standard Time": -7 * 60,
  "Mountain Standard Time (Mexico)": -7 * 60,
  "US Mountain Standard Time": -7 * 60,
  "Canada Central Standard Time": -6 * 60,
  "Central America Standard Time": -6 * 60,
  "Central Standard Time": -6 * 60,
  "Eastern Standard Time": -5 * 60,
  "SA Pacific Standard Time": -5 * 60,
  "US Eastern Standard Time": -5 * 60,
  "Venezuela Standard Time": -4 * 60,
  "Atlantic Standard Time": -4 * 60,
  "Central Brazilian Standard Time": -4 * 60,
  "Pacific SA Standard Time": -4 * 60,
  "Paraguay Standard Time": -4 * 60,
  "SA Western Standard Time": -4 * 60,
  "Newfoundland Standard Time": -3 * 60,
  "Bahia Standard Time": -3 * 60,
  "Argentina Standard Time": -3 * 60,
  "E. South America Standard Time": -3 * 60,
  "Greenland Standard Time": -3 * 60,
  "Montevideo Standard Time": -3 * 60,
  "SA Eastern Standard Time": -3 * 60,
  "UTC-02	": -2 * 60,
  "Azores Standard Time": -1 * 60,
  "Cape Verde Standard Time	": -1 * 60,
  "GMT Standard Time": 0,
  "Greenwich Standard Time": 0,
  "Morocco Standard Time": 0,
  "UTC": 0 * 60,
  "Central Europe Standard Time": 1 * 60,
  "Central European Standard Time": 1 * 60,
  "Namibia Standard Time": 1 * 60,
  "Romance Standard Time": 1 * 60,
  "W. Central Africa Standard Time": 1 * 60,
  "W. Europe Standard Time": 1 * 60,
  "Egypt Standard Time": 2 * 60,
  "FLE Standard Time": 2 * 60,
  "GTB Standard Time": 2 * 60,
  "Israel Standard Time": 2 * 60,
  "Libya Standard Time": 2 * 60,
  "Middle East Standard Time": 2 * 60,
  "South Africa Standard Time": 2 * 60,
  "Syria Standard Time": 2 * 60,
  "Turkey Standard Time": 2 * 60,
  "Arab Standard Time": 3 * 60,
  "Arabic Standard Time": 3 * 60,
  "Belarus Standard Time": 3 * 60,
  "E. Africa Standard Time": 3 * 60,
  "Jordan Standard Time": 3 * 60,
  "Kaliningrad Standard Time": 3 * 60,
  "Iran Standard Time	": 3 * 60,
  "Arabian Standard Time": 4 * 60,
  "Azerbaijan Standard Time": 4 * 60,
  "Caucasus Standard Time": 4 * 60,
  "Georgian Standard Time": 4 * 60,
  "Mauritius Standard Time": 4 * 60,
  "Russia Time Zone 3": 4 * 60,
  "Russian Standard Time": 4 * 60,
  "Afghanistan Standard Time": 4 * 60 + 30, // +4:30
  "Pakistan Standard Time": 5 * 60,
  "West Asia Standard Time": 5 * 60,
  "India Standard Time": 5 * 60 + 30,
  "Sri Lanka Standard Time": 5 * 60 + 30,
  "Nepal Standard Time": 5 * 60 + 45,
  "Bangladesh Standard Time": 6 * 60,
  "Central Asia Standard Time": 6 * 60,
  "Ekaterinburg Standard Time": 6 * 60,
  "Myanmar Standard Time": 6 * 60 + 30,
  //"N. Central Asia Standard Time": 7 * 60,
  "SE Asia Standard Time": 7 * 60,
  "China Standard Time": 8 * 60,
  "North Asia Standard Time": 8 * 60,
  "Singapore Standard Time": 8 * 60,
  "Taipei Standard Time": 8 * 60,
  "Ulaanbaatar Standard Time": 8 * 60,
  "W. Australia Standard Time": 8 * 60,
  "Korea Standard Time": 9 * 60,
  "North Asia East Standard Time": 8 * 60,
  "AUS Central Standard Time`": 9 * 60 + 30,
  "Tokyo Standard Time": 9 * 60,
  "Cen. Australia Standard Time	": 9 * 60 + 30,
  "AUS Eastern Standard Time": 10 * 60,
  "E. Australia Standard Time": 10 * 60,
  "Tasmania Standard Time": 10 * 60,
  "West Pacific Standard Time": 10 * 60,
  "Yakutsk Standard Time": 10 * 60,
  "Central Pacific Standard Time": 11 * 60,
  "Russia Time Zone 10": 11 * 60,
  "Vladivostok Standard Time": 11 * 60,
  "Fiji Standard Time": 12 * 60,
  "Magadan Standard Time": 12 * 60,
  "New Zealand Standard Time": 12 * 60,
  "Russia Time Zone 11": 12 * 60,
  "UTC+12": 12 * 60,
  "Tonga Standard Time": 13 * 60,
  "Line Islands Standard Time": 14 * 60
};
